name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    uses: mrkkrp/haskell-ci/.github/workflows/haskell-ci.yml@master
    with:
      pre-test-script: |
        docker pull kennethreitz/httpbin
        docker run -p 1234:80 kennethreitz/httpbin &
